# Generated by Django 6.0.5 on 2026-05-16 22:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0006_scenario_requires_team_participation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionparticipant',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Still a member of this mission (not removed); not WebSocket presence.'),
        ),
        migrations.AlterField(
            model_name='missionparticipant',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, help_text='Last WebSocket heartbeat or connect; used for is_online presence.', null=True),
        ),
        migrations.AddIndex(
            model_name='incidentevent',
            index=models.Index(fields=['run', 'timestamp'], name='simulations_run_id_2302a1_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentrun',
            index=models.Index(fields=['status', '-started_at'], name='simulations_status_57b2e5_idx'),
        ),
        migrations.AddIndex(
            model_name='missionparticipant',
            index=models.Index(fields=['run', 'user'], name='simulations_run_id_9d42d3_idx'),
        ),
        migrations.AddIndex(
            model_name='threatnode',
            index=models.Index(fields=['scenario', 'phase'], name='simulations_scenari_25a70a_idx'),
        ),
    ]
